# Generated by Django 4.0.4 on 2022-06-15 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('subtitle', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=2000)),
                ('author', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='imagenes_posts')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
